FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    netcat-openbsd \
  && rm -rf /var/lib/apt/lists/*

# Install python deps (dev)
COPY backend/requirements/ /tmp/requirements/
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r /tmp/requirements/dev.txt

EXPOSE 8000
