# Generated by Django 5.2.9 on 2026-02-15 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImageModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='WishlistProduct',
            new_name='WishlistProductModel',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='shop_produc_status_4c4250_idx',
            old_name='shop_produc_status_f944b2_idx',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='shop_produc_price_f806fe_idx',
            old_name='shop_produc_price_3b79b5_idx',
        ),
    ]
